-sverilog
D:\rs_mlsd_4arch_compare_adaptive_k_chaware\branch_centric_pam8_variant\symbol_lut_mode_8b.sv
D:\rs_mlsd_4arch_compare_adaptive_k_chaware\branch_centric_pam8_variant\survivor_mem_flat.sv
D:\rs_mlsd_4arch_compare_adaptive_k_chaware\branch_centric_pam8_variant\traceback_flat.sv
D:\rs_mlsd_4arch_compare_adaptive_k_chaware\branch_centric_pam8_variant\fir_siso_wide.sv
D:\rs_mlsd_4arch_compare_adaptive_k_chaware\branch_centric_pam8_variant\cmp_allfs_mlsd_core_lane_8b.sv
D:\rs_mlsd_4arch_compare_adaptive_k_chaware\branch_centric_pam8_variant\tb_mlsd_allfs_debug_1lane.sv
