`timescale 1ns/1ps

// ============================================================================
// trunc16_to_8_64lane (explicit ports, inverse of ext8_to_16_64lane)
// - 16bit signed -> 8bit signed
// - assumes input was generated by <<<8 full-scale mapping
// - arithmetic right shift >>>8
// ============================================================================

module trunc16_to_8_64lane (

    input  signed [15:0] din16_0,
    input  signed [15:0] din16_1,
    input  signed [15:0] din16_2,
    input  signed [15:0] din16_3,
    input  signed [15:0] din16_4,
    input  signed [15:0] din16_5,
    input  signed [15:0] din16_6,
    input  signed [15:0] din16_7,
    input  signed [15:0] din16_8,
    input  signed [15:0] din16_9,
    input  signed [15:0] din16_10,
    input  signed [15:0] din16_11,
    input  signed [15:0] din16_12,
    input  signed [15:0] din16_13,
    input  signed [15:0] din16_14,
    input  signed [15:0] din16_15,
    input  signed [15:0] din16_16,
    input  signed [15:0] din16_17,
    input  signed [15:0] din16_18,
    input  signed [15:0] din16_19,
    input  signed [15:0] din16_20,
    input  signed [15:0] din16_21,
    input  signed [15:0] din16_22,
    input  signed [15:0] din16_23,
    input  signed [15:0] din16_24,
    input  signed [15:0] din16_25,
    input  signed [15:0] din16_26,
    input  signed [15:0] din16_27,
    input  signed [15:0] din16_28,
    input  signed [15:0] din16_29,
    input  signed [15:0] din16_30,
    input  signed [15:0] din16_31,
    input  signed [15:0] din16_32,
    input  signed [15:0] din16_33,
    input  signed [15:0] din16_34,
    input  signed [15:0] din16_35,
    input  signed [15:0] din16_36,
    input  signed [15:0] din16_37,
    input  signed [15:0] din16_38,
    input  signed [15:0] din16_39,
    input  signed [15:0] din16_40,
    input  signed [15:0] din16_41,
    input  signed [15:0] din16_42,
    input  signed [15:0] din16_43,
    input  signed [15:0] din16_44,
    input  signed [15:0] din16_45,
    input  signed [15:0] din16_46,
    input  signed [15:0] din16_47,
    input  signed [15:0] din16_48,
    input  signed [15:0] din16_49,
    input  signed [15:0] din16_50,
    input  signed [15:0] din16_51,
    input  signed [15:0] din16_52,
    input  signed [15:0] din16_53,
    input  signed [15:0] din16_54,
    input  signed [15:0] din16_55,
    input  signed [15:0] din16_56,
    input  signed [15:0] din16_57,
    input  signed [15:0] din16_58,
    input  signed [15:0] din16_59,
    input  signed [15:0] din16_60,
    input  signed [15:0] din16_61,
    input  signed [15:0] din16_62,
    input  signed [15:0] din16_63,

    output signed [7:0] dout8_0,
    output signed [7:0] dout8_1,
    output signed [7:0] dout8_2,
    output signed [7:0] dout8_3,
    output signed [7:0] dout8_4,
    output signed [7:0] dout8_5,
    output signed [7:0] dout8_6,
    output signed [7:0] dout8_7,
    output signed [7:0] dout8_8,
    output signed [7:0] dout8_9,
    output signed [7:0] dout8_10,
    output signed [7:0] dout8_11,
    output signed [7:0] dout8_12,
    output signed [7:0] dout8_13,
    output signed [7:0] dout8_14,
    output signed [7:0] dout8_15,
    output signed [7:0] dout8_16,
    output signed [7:0] dout8_17,
    output signed [7:0] dout8_18,
    output signed [7:0] dout8_19,
    output signed [7:0] dout8_20,
    output signed [7:0] dout8_21,
    output signed [7:0] dout8_22,
    output signed [7:0] dout8_23,
    output signed [7:0] dout8_24,
    output signed [7:0] dout8_25,
    output signed [7:0] dout8_26,
    output signed [7:0] dout8_27,
    output signed [7:0] dout8_28,
    output signed [7:0] dout8_29,
    output signed [7:0] dout8_30,
    output signed [7:0] dout8_31,
    output signed [7:0] dout8_32,
    output signed [7:0] dout8_33,
    output signed [7:0] dout8_34,
    output signed [7:0] dout8_35,
    output signed [7:0] dout8_36,
    output signed [7:0] dout8_37,
    output signed [7:0] dout8_38,
    output signed [7:0] dout8_39,
    output signed [7:0] dout8_40,
    output signed [7:0] dout8_41,
    output signed [7:0] dout8_42,
    output signed [7:0] dout8_43,
    output signed [7:0] dout8_44,
    output signed [7:0] dout8_45,
    output signed [7:0] dout8_46,
    output signed [7:0] dout8_47,
    output signed [7:0] dout8_48,
    output signed [7:0] dout8_49,
    output signed [7:0] dout8_50,
    output signed [7:0] dout8_51,
    output signed [7:0] dout8_52,
    output signed [7:0] dout8_53,
    output signed [7:0] dout8_54,
    output signed [7:0] dout8_55,
    output signed [7:0] dout8_56,
    output signed [7:0] dout8_57,
    output signed [7:0] dout8_58,
    output signed [7:0] dout8_59,
    output signed [7:0] dout8_60,
    output signed [7:0] dout8_61,
    output signed [7:0] dout8_62,
    output signed [7:0] dout8_63
);

    // arithmetic right shift (inverse of <<<8)
    assign dout8_0  = din16_0  >>> 8;
    assign dout8_1  = din16_1  >>> 8;
    assign dout8_2  = din16_2  >>> 8;
    assign dout8_3  = din16_3  >>> 8;
    assign dout8_4  = din16_4  >>> 8;
    assign dout8_5  = din16_5  >>> 8;
    assign dout8_6  = din16_6  >>> 8;
    assign dout8_7  = din16_7  >>> 8;
    assign dout8_8  = din16_8  >>> 8;
    assign dout8_9  = din16_9  >>> 8;
    assign dout8_10 = din16_10 >>> 8;
    assign dout8_11 = din16_11 >>> 8;
    assign dout8_12 = din16_12 >>> 8;
    assign dout8_13 = din16_13 >>> 8;
    assign dout8_14 = din16_14 >>> 8;
    assign dout8_15 = din16_15 >>> 8;
    assign dout8_16 = din16_16 >>> 8;
    assign dout8_17 = din16_17 >>> 8;
    assign dout8_18 = din16_18 >>> 8;
    assign dout8_19 = din16_19 >>> 8;
    assign dout8_20 = din16_20 >>> 8;
    assign dout8_21 = din16_21 >>> 8;
    assign dout8_22 = din16_22 >>> 8;
    assign dout8_23 = din16_23 >>> 8;
    assign dout8_24 = din16_24 >>> 8;
    assign dout8_25 = din16_25 >>> 8;
    assign dout8_26 = din16_26 >>> 8;
    assign dout8_27 = din16_27 >>> 8;
    assign dout8_28 = din16_28 >>> 8;
    assign dout8_29 = din16_29 >>> 8;
    assign dout8_30 = din16_30 >>> 8;
    assign dout8_31 = din16_31 >>> 8;
    assign dout8_32 = din16_32 >>> 8;
    assign dout8_33 = din16_33 >>> 8;
    assign dout8_34 = din16_34 >>> 8;
    assign dout8_35 = din16_35 >>> 8;
    assign dout8_36 = din16_36 >>> 8;
    assign dout8_37 = din16_37 >>> 8;
    assign dout8_38 = din16_38 >>> 8;
    assign dout8_39 = din16_39 >>> 8;
    assign dout8_40 = din16_40 >>> 8;
    assign dout8_41 = din16_41 >>> 8;
    assign dout8_42 = din16_42 >>> 8;
    assign dout8_43 = din16_43 >>> 8;
    assign dout8_44 = din16_44 >>> 8;
    assign dout8_45 = din16_45 >>> 8;
    assign dout8_46 = din16_46 >>> 8;
    assign dout8_47 = din16_47 >>> 8;
    assign dout8_48 = din16_48 >>> 8;
    assign dout8_49 = din16_49 >>> 8;
    assign dout8_50 = din16_50 >>> 8;
    assign dout8_51 = din16_51 >>> 8;
    assign dout8_52 = din16_52 >>> 8;
    assign dout8_53 = din16_53 >>> 8;
    assign dout8_54 = din16_54 >>> 8;
    assign dout8_55 = din16_55 >>> 8;
    assign dout8_56 = din16_56 >>> 8;
    assign dout8_57 = din16_57 >>> 8;
    assign dout8_58 = din16_58 >>> 8;
    assign dout8_59 = din16_59 >>> 8;
    assign dout8_60 = din16_60 >>> 8;
    assign dout8_61 = din16_61 >>> 8;
    assign dout8_62 = din16_62 >>> 8;
    assign dout8_63 = din16_63 >>> 8;

endmodule